version = "0.7.2"
build = 327674

[files]
"content/GameParams.data" = "510ffb5f40ae6d370c13"
"gui/consumables/ammo_Bomber.png" = "7cbb77251f542fcbb90c"
"gui/consumables/ammo_Bomber_deepwater.png" = "c711360d5b048c1aee5d"
"gui/consumables/ammo_Dive.png" = "effa02f657eb2e9768b4"
"gui/consumables/ammo_Dive_AP.png" = "a65c23425e09ce526bd4"
"gui/consumables/ammo_Fighter.png" = "638d7cc577c93fff090d"
"gui/consumables/ammo_ap.png" = "2bc02042b1d7d612effa"
"gui/consumables/ammo_ap_2x.png" = "7bf5c6aa3a7cc93d1f45"
"gui/consumables/ammo_he.png" = "6b52f825e91d2a3da54a"
"gui/consumables/ammo_he_2x.png" = "3d349ffccf0b988db5f9"
"gui/consumables/ammo_torpedo.png" = "5e73fdfb635b1b9a704e"
"gui/consumables/ammo_torpedo_deepwater.png" = "775cff43bf910b93bb59"
"gui/consumables/consumable_PCY001_CrashCrew.png" = "9737e79b1c33b86820cb"
"gui/consumables/consumable_PCY001_CrashCrew_empty.png" = "353952ee2e69120cb2b8"
"gui/consumables/consumable_PCY002_RegenCrew.png" = "c61df1a6604d79ef1489"
"gui/consumables/consumable_PCY002_RegenCrew_empty.png" = "c2fbbca5366be442c389"
"gui/consumables/consumable_PCY003_AirDefenseDisp.png" = "87d6f4d56422de58bd2a"
"gui/consumables/consumable_PCY003_AirDefenseDisp_empty.png" = "0639365b92a16136daef"
"gui/consumables/consumable_PCY004_Fighter.png" = "408a343e4d9ba94764e8"
"gui/consumables/consumable_PCY004_Fighter_empty.png" = "7b749bbad18b3808a27d"
"gui/consumables/consumable_PCY005_Spotter.png" = "19db12d387e932d8074f"
"gui/consumables/consumable_PCY005_Spotter_empty.png" = "ec52a719c41bd114901f"
"gui/consumables/consumable_PCY006_SmokeGenerator.png" = "188f29197f13bf76b7ba"
"gui/consumables/consumable_PCY006_SmokeGenerator_empty.png" = "d0c0f391449d1bae9590"
"gui/consumables/consumable_PCY007_SpeedBooster.png" = "57d2654b2fce0d4c9cf4"
"gui/consumables/consumable_PCY007_SpeedBooster_empty.png" = "1cca4af19612482657d7"
"gui/consumables/consumable_PCY008_SonarSearch.png" = "b0b85e341421e12be68f"
"gui/consumables/consumable_PCY008_SonarSearch_empty.png" = "82a0d48049be90f049bd"
"gui/consumables/consumable_PCY009_CrashCrewPremium.png" = "d86370242fc43123cc04"
"gui/consumables/consumable_PCY009_CrashCrewPremium_empty.png" = "e35e9565b82d0c8580ab"
"gui/consumables/consumable_PCY010_RegenCrewPremium.png" = "dfb2d390a17caf11881c"
"gui/consumables/consumable_PCY010_RegenCrewPremium_empty.png" = "7cb75c44c54d7c2c57c2"
"gui/consumables/consumable_PCY011_AirDefenseDispPremium.png" = "8146cc5df025829d55c6"
"gui/consumables/consumable_PCY011_AirDefenseDispPremium_empty.png" = "2a0ffc783da32e7c83f0"
"gui/consumables/consumable_PCY012_FighterPremium.png" = "71ab54cdf0027bef7346"
"gui/consumables/consumable_PCY012_FighterPremium_empty.png" = "83d2867c0f74a22737ec"
"gui/consumables/consumable_PCY013_SpotterPremium.png" = "322ec731936dbd7cff33"
"gui/consumables/consumable_PCY013_SpotterPremium_empty.png" = "0719070887c316dda6a5"
"gui/consumables/consumable_PCY014_SmokeGeneratorPremium.png" = "616b5b293ff0f07d0c7e"
"gui/consumables/consumable_PCY014_SmokeGeneratorPremium_empty.png" = "5f8b47157ed69792bf18"
"gui/consumables/consumable_PCY015_SpeedBoosterPremium.png" = "0b3e18b8261b67e8d024"
"gui/consumables/consumable_PCY015_SpeedBoosterPremium_empty.png" = "1466d6217482a05641a5"
"gui/consumables/consumable_PCY016_SonarSearchPremium.png" = "7f8958c7ff518f17bd5d"
"gui/consumables/consumable_PCY016_SonarSearchPremium_empty.png" = "a6e0603dfe3a864ff8f3"
"gui/consumables/consumable_PCY017_TorpedoReloader.png" = "836b8fb7875610a2b7a5"
"gui/consumables/consumable_PCY017_TorpedoReloader_empty.png" = "83c908aa0b77d73a36ab"
"gui/consumables/consumable_PCY018_TorpedoReloaderPremium.png" = "02407927372d76c03082"
"gui/consumables/consumable_PCY018_TorpedoReloaderPremium_empty.png" = "0b79390f8551796c7027"
"gui/consumables/consumable_PCY019_RLSSearch.png" = "18323166368eeb5c893a"
"gui/consumables/consumable_PCY019_RLSSearch_empty.png" = "0b34492cf9821fcf91ab"
"gui/consumables/consumable_PCY020_RLSSearchPremium.png" = "5f211ad468f58c0a2884"
"gui/consumables/consumable_PCY020_RLSSearchPremium_empty.png" = "bd26d89d1677372587ec"
"gui/consumables/consumable_PCY021_MGReloader.png" = "0d445caa5f59082b654e"
"gui/consumables/consumable_PCY021_MGReloader_empty.png" = "c427bcc701cdfde51946"
"gui/consumables/consumable_PXY001_MindControl.png" = "cf7d80ef8043c31927d2"
"gui/consumables/consumable_PXY001_MindControl_empty.png" = "daaa67acea3d907edf31"
"gui/consumables/consumable_PXY002_Agggr.png" = "1cc5ed17e6a892831b62"
"gui/consumables/consumable_PXY002_Agggr_empty.png" = "c2b19254c203764b7aa5"
"gui/consumables/consumable_PXY003_Protection.png" = "8afa2cffaa210ddef8c4"
"gui/consumables/consumable_PXY003_Protection_empty.png" = "cc49ed554e221189aad4"
"gui/consumables/consumable_PXY004_HealAura.png" = "2e1ea393237b0886d9a5"
"gui/consumables/consumable_PXY004_HealAura_empty.png" = "491cdd72abb1991457a1"
"gui/consumables/consumable_PXY004_HealAural_empty.png" = "ee956e668e98f4017a56"
"gui/consumables/consumable_PXY005_HealAll.png" = "41762c504807c0de230b"
"gui/consumables/consumable_PXY005_HealAll_empty.png" = "9d36a92483427434aecc"
"gui/consumables/consumable_PXY006_CrashAll.png" = "ee13839bbf59afd3734b"
"gui/consumables/consumable_PXY006_CrashAll_empty.png" = "69889bb0866aa5d3c5ae"
"gui/consumables/consumable_PXY007_SpeedBooster.png" = "670245e3f55cc607389d"
"gui/consumables/consumable_PXY007_SpeedBooster_empty.png" = "77b48528a25d264d01a4"
"gui/consumables/consumable_PXY008_HolyWeapon.png" = "b46ab4dc85381dcad522"
"gui/consumables/consumable_PXY008_HolyWeapon_empty.png" = "f82dee11b492d368b1f4"
"gui/consumables/consumable_PXY009_TorpedoReloader.png" = "32b6059898f92e86ec54"
"gui/consumables/consumable_PXY009_TorpedoReloader_empty.png" = "cfbaec8e03240ef0b876"
"gui/consumables/consumable_PXY010_RLSSearch.png" = "04771f31cba9c0adbb0e"
"gui/consumables/consumable_PXY010_RLSSearch_empty.png" = "fc69ff9f61fb2f61f7d8"
"gui/consumables/consumable_PXY011_SonarSearch.png" = "7f8958c7ff518f17bd5d"
"gui/consumables/consumable_PXY011_SonarSearch_empty.png" = "a6e0603dfe3a864ff8f3"
"gui/consumables/consumable_PXY012_SmokeGenerator.png" = "a5e04368960749672dcc"
"gui/consumables/consumable_PXY012_SmokeGenerator_empty.png" = "c30a608a305e7ee18432"
"gui/consumables/consumable_PXY013_CrashCrew.png" = "f2231fd6b9083bcd72ed"
"gui/consumables/consumable_PXY013_CrashCrew_empty.png" = "108abeceb63db3763a10"
"gui/consumables/consumable_PXY014_RegenCrew.png" = "94e4d558722d532279cf"
"gui/consumables/consumable_PXY014_RegenCrew_empty.png" = "a31642d035d7c3f42228"
"gui/consumables/consumable_PXY101_MindControlPremium.png" = "30265e1f3f218dbb0544"
"gui/consumables/consumable_PXY101_MindControlPremium_empty.png" = "c20baeeda14110bf188e"
"gui/consumables/consumable_PXY103_ProtectionPremium.png" = "d2bb0453bdf819ece228"
"gui/consumables/consumable_PXY103_ProtectionPremium_empty.png" = "3cf679eebc8cce25db97"
"gui/consumables/consumable_PXY104_HealAuraPremium.png" = "219f0d270103d2da5383"
"gui/consumables/consumable_PXY104_HealAuraPremium_empty.png" = "c61fffa05bd3a672705b"
"gui/consumables/consumable_PXY105_HealAllPremium.png" = "dc25ca07a0af41436675"
"gui/consumables/consumable_PXY105_HealAllPremium_empty.png" = "9c8b19eda02273470440"
"gui/consumables/consumable_PXY106_CrashAllPremium.png" = "c8c3ac215711a0289de7"
"gui/consumables/consumable_PXY106_CrashAllPremium_empty.png" = "66d685fcee2c36abd189"
"gui/consumables/consumable_PXY107_SpeedBoosterPremium.png" = "42bfb2cf902af2199685"
"gui/consumables/consumable_PXY107_SpeedBoosterPremium_empty.png" = "3bf1ba693a1ff17e191a"
"gui/consumables/consumable_PXY108_HolyWeaponPremium.png" = "51b6081c2c37f1640327"
"gui/consumables/consumable_PXY108_HolyWeaponPremium_empty.png" = "5df92d335d4e959ed6e3"
"gui/consumables/consumable_PXY109_TorpedoReloaderPremium.png" = "dee000593055a99f3fd1"
"gui/consumables/consumable_PXY109_TorpedoReloaderPremium_empty.png" = "8096367a0e2992753bb9"
"gui/consumables/consumable_PXY110_RLSSearchPremium.png" = "95a86082772a8153d9b9"
"gui/consumables/consumable_PXY110_RLSSearchPremium_empty.png" = "6c979b0ecba15d18fb8e"
"gui/consumables/consumable_PXY112_SmokeGeneratorPremium.png" = "6a09e3cc8df45144a8a5"
"gui/consumables/consumable_PXY112_SmokeGeneratorPremium_empty.png" = "5b96c5d4f6aba0501c86"
"gui/consumables/consumable_PXY113_CrashCrewPremium.png" = "475776af509ffb8829dc"
"gui/consumables/consumable_PXY113_CrashCrewPremium_empty.png" = "faae0c63427105bdb92c"
"gui/consumables/consumable_PXY114_RegenCrewPremium.png" = "2f215b74ed8612c4c3a8"
"gui/consumables/consumable_PXY114_RegenCrewPremium_empty.png" = "f2663d855fdc8486b8c1"
"gui/consumables/unit_carrier.png" = "a947935a84e8be1f1234"
"scripts/entities.xml" = "32fb1d2f01eb862962f8"
"scripts/entity_defs/Account.def" = "7cc1d3340d07dcb8cf83"
"scripts/entity_defs/AccountController.def" = "484c0a1ed0d96cd4d02b"
"scripts/entity_defs/Avatar.def" = "3b044130f05e12d211e3"
"scripts/entity_defs/BattleLogic.def" = "31e9909ac845c1efc2b6"
"scripts/entity_defs/Building.def" = "60d9a197de0c192a4e3c"
"scripts/entity_defs/Fog.def" = "d806fed1bef187ebae52"
"scripts/entity_defs/Login.def" = "0e1f1873364a84282046"
"scripts/entity_defs/MasterChanger.def" = "fa6f86262d6750c03fc2"
"scripts/entity_defs/OfflineEntity.def" = "eca404792fe886ef0d90"
"scripts/entity_defs/ReplayLeech.def" = "dd11f114424ac91f09ca"
"scripts/entity_defs/SmokeScreen.def" = "c736fafa1915059244d5"
"scripts/entity_defs/Vehicle.def" = "41c2dcb4bba5da12ee24"
"scripts/entity_defs/Weather.def" = "7ba78f9c2545c3bd566e"
"scripts/entity_defs/alias.xml" = "64648dfebd601dba91ae"
"scripts/entity_defs/interfaces/AccountEditor.def" = "e66183f509f61409af3d"
"scripts/entity_defs/interfaces/AccountPData.def" = "f2f3b3bdaf46846c7818"
"scripts/entity_defs/interfaces/AccountReady.def" = "ed37c01ec141cf4bf1a6"
"scripts/entity_defs/interfaces/AirDefenceOwner.def" = "97a33f7669d000131772"
"scripts/entity_defs/interfaces/AtbaOwner.def" = "a1e18db00e8ea0c3ddad"
"scripts/entity_defs/interfaces/AviationOwner.def" = "1ba47c0cf699b9534cb6"
"scripts/entity_defs/interfaces/BattleStarter.def" = "1c29121f06215d8a0e20"
"scripts/entity_defs/interfaces/DebugDrawEntity.def" = "de81d72db39f8bd7d8f6"
"scripts/entity_defs/interfaces/EntityLookuper.def" = "14270ade8f00f95bdcfb"
"scripts/entity_defs/interfaces/HitLocationManagerOwner.def" = "73dca91febb6a6e538e1"
"scripts/entity_defs/interfaces/StatsPublisher.def" = "9188dbd43afbf3363482"
"scripts/entity_defs/interfaces/VisionOwner.def" = "2f99bdecd24c25881b23"
"scripts/entity_defs/interfaces/VoiceChatClient.def" = "8a41107aa161753d9de2"
"scripts/entity_defs/interfaces/WalletOwner.def" = "21fee9feee94828adbd6"
"scripts/entity_defs/interfaces/WalletProperties.def" = "95fb1a7a8a0368190935"
"scripts/entity_defs/interfaces/WeatherOwner.def" = "207a4614d4e5d384d3ad"
"spaces/00_CO_ocean/minimap.png" = "004fa519e5343e86a03b"
"spaces/00_CO_ocean/minimap_water.png" = "4feaae35fbf91a692ae7"
"spaces/01_solomon_islands/minimap.png" = "eec21f3f5e289ad2eefb"
"spaces/01_solomon_islands/minimap_water.png" = "fa732417e6567f4bcdba"
"spaces/04_Archipelago/minimap.png" = "14cde2c4a33739f3a26c"
"spaces/04_Archipelago/minimap_water.png" = "bb0a2b8cac7575c74ba0"
"spaces/05_Ring/minimap.png" = "bc44da4eec24a8173699"
"spaces/05_Ring/minimap_water.png" = "fbba472ec5c33a8f4a69"
"spaces/08_NE_passage/minimap.png" = "c161e5a73643e74c5279"
"spaces/08_NE_passage/minimap_water.png" = "dadea954517ca4a21175"
"spaces/10_NE_big_race/minimap.png" = "bd1fdd5e025edb52e9ab"
"spaces/10_NE_big_race/minimap_water.png" = "074083053aab069db670"
"spaces/13_OC_new_dawn/minimap.png" = "155f63a2ab41619be36e"
"spaces/13_OC_new_dawn/minimap_water.png" = "706ed5d53962cc0b2715"
"spaces/14_Atlantic/minimap.png" = "54eda34e42de3ac37b11"
"spaces/14_Atlantic/minimap_water.png" = "55169a01384d42e4e62b"
"spaces/15_NE_north/minimap.png" = "7b581bde7913a98ea1df"
"spaces/15_NE_north/minimap_water.png" = "b6799edd3fac009e24a7"
"spaces/16_OC_bees_to_honey/minimap.png" = "4ca2b3d6b78f8b0e04d9"
"spaces/16_OC_bees_to_honey/minimap_water.png" = "fe3e5350c90b7adb588e"
"spaces/17_NA_fault_line/minimap.png" = "7ad91f9864e55bb9206d"
"spaces/17_NA_fault_line/minimap_water.png" = "3e417aca6f2975b8840d"
"spaces/18_NE_ice_islands/minimap.png" = "fe7878af658297e6adf2"
"spaces/18_NE_ice_islands/minimap_water.png" = "03bb89709549d63eec2c"
"spaces/19_OC_prey/minimap.png" = "0f6767f579f70c01900d"
"spaces/19_OC_prey/minimap_water.png" = "3511edffcd9be9f953e3"
"spaces/20_NE_two_brothers/minimap.png" = "9f94361633c2e541c8b5"
"spaces/20_NE_two_brothers/minimap_water.png" = "805e9cab0300551d455a"
"spaces/22_tierra_del_fuego/minimap.png" = "e27ab6de442469186040"
"spaces/22_tierra_del_fuego/minimap_water.png" = "693ecf762a0f51aa274f"
"spaces/23_Shards/minimap.png" = "b618f9446156d82aba87"
"spaces/23_Shards/minimap_water.png" = "03ff085ab0ca9af9561d"
"spaces/25_sea_hope/minimap.png" = "1a3874abf06cbb4d21db"
"spaces/25_sea_hope/minimap_water.png" = "3e14f635ce7c08309271"
"spaces/28_naval_mission/minimap.png" = "96e633fc146a76cd7fab"
"spaces/28_naval_mission/minimap_water.png" = "0765223ba8f5c1ebcc0a"
"spaces/33_new_tierra/minimap.png" = "a8938eb8ec4dc907b2ab"
"spaces/33_new_tierra/minimap_water.png" = "7c0380ab34aca12c073f"
"spaces/33_new_tierra/space.settings" = "e2e9e2876d8b84b779cd"
"spaces/34_OC_islands/minimap.png" = "fb8311e3ef13801157e5"
"spaces/34_OC_islands/minimap_water.png" = "51efe1c16da4c7e1bd2a"
"spaces/34_OC_islands/space.settings" = "858833fde52dc0ff4488"
"spaces/35_NE_north_winter/minimap.png" = "e478d7bb669061eaa730"
"spaces/35_NE_north_winter/minimap_water.png" = "9f395649680e6586a5f8"
"spaces/37_Ridge/minimap.png" = "b3e5854d902a603a32d5"
"spaces/37_Ridge/minimap_water.png" = "8196be687369f100fc2e"
"spaces/38_Canada/minimap.png" = "877e75474def1f5975f7"
"spaces/38_Canada/minimap_water.png" = "1471c934de261edbe42f"
"spaces/40_Okinawa/minimap.png" = "ca6d1eb958c629f5bbf8"
"spaces/40_Okinawa/minimap_water.png" = "14341ee0ba03f2e38ace"
"spaces/41_Conquest/minimap.png" = "961ce64bc62fd9699b11"
"spaces/41_Conquest/minimap_water.png" = "0316fd050c447358c44e"
"spaces/42_Neighbors/minimap.png" = "7207ef0111adb236ea75"
"spaces/42_Neighbors/minimap_water.png" = "e4ca0fc0903158a65a8e"
"spaces/44_Path_warrior/minimap.png" = "6c7e4fb8f486f902f144"
"spaces/44_Path_warrior/minimap_water.png" = "626383a4e6d1b7c8cde9"
"spaces/45_Zigzag/minimap.png" = "b706fd60b2a2d5410812"
"spaces/45_Zigzag/minimap_water.png" = "039cb5dc5ea433843951"
"spaces/46_Estuary/minimap.png" = "1259534ed9a57e737bd3"
"spaces/46_Estuary/minimap_water.png" = "1be9dc5cea6d77afc0cb"
"spaces/47_Sleeping_Giant/minimap.png" = "7e8a99da96849d19e08c"
"spaces/47_Sleeping_Giant/minimap_water.png" = "c034acf9f2888e3c1dba"
"spaces/50_Gold_harbor/minimap.png" = "d460c684799e29891998"
"spaces/50_Gold_harbor/minimap_water.png" = "72aaf3f2d6934ffcae9e"
"spaces/Dock/space.settings" = "37853c980f328b9d651f"
"spaces/dock_Hamburg/space.settings" = "48ec5892f619226c3cd6"
"spaces/dock_Marseille/space.settings" = "02ad026a4ee6630898de"
"spaces/dock_dry/space.settings" = "26b6f26c2eead1256890"
"spaces/i01_tutorial/minimap.png" = "2900e1295e9add987db6"
"spaces/i01_tutorial/minimap_water.png" = "86c52a753eccec08ca99"
"spaces/i01_tutorial/space.settings" = "b4a0df8c9b461c878d47"
"spaces/r01_military_navigation/minimap.png" = "724747b6e379ca5ecf78"
"spaces/r01_military_navigation/minimap_water.png" = "9f89087d77c36d901efe"
"spaces/s01_NavalBase/minimap.png" = "175df4403dd73151b791"
"spaces/s01_NavalBase/minimap_water.png" = "c98fd11d5aa177db45ec"
"spaces/s02_Naval_Defense/minimap.png" = "1798b110508f6e7d6f4a"
"spaces/s02_Naval_Defense/minimap_water.png" = "7108f44ff11ba0049cc2"
"spaces/s03_Labyrinth/minimap.png" = "b5ae6f12f3ff0b73c3bc"
"spaces/s03_Labyrinth/minimap_water.png" = "c034acf9f2888e3c1dba"
"spaces/s06_Atoll/minimap.png" = "2750c71268d7802a082c"
"spaces/s06_Atoll/minimap_water.png" = "3c6e91a850675a7e7973"
"spaces/s07_Advance/minimap.png" = "1ffde5b875ab3592cfe2"
"spaces/s07_Advance/minimap_water.png" = "3e417aca6f2975b8840d"
"spaces/s09_LePVE/minimap.png" = "ba2905b3deeb61a78aec"
"spaces/s09_LePVE/minimap_water.png" = "378dbb9d05c1c8a9429a"
